keys:
  - &minz-vultr-nix-0 age1zfx0aepvzs6sz7fp4ajvv9ktl2qa4vxeqz8tk67ypvclks9paqts52e0d2

  - &minz-vultr-nix-1 age1y50jdycujl38fgvmsj3gqqtpreuuh9k8caxu3m4tef44nm2tyqss5glvlg

  - &minz-home-nix-0 age129u59rl8hmj9ahvh62lglucu8lag65jasdd7yc2z5hfg8yletajs3n5psa

  - &minz-obs-0 age1d24umdyn0v8gfdvrtxug02ddjfv38u5n5strm846mfu2q4fktgaq6ptlqd

  - &minz-authentik-0 age1tk2thlt86mrl47d44u3f47v90mpp2w6f7ccmhzyjy9ycxtr7ne4qu3a73u

  - &minz-media-0 age1ehkwt0l6c22glvv9tc35ktece9rzxqelgxvklwk9klkkhd38gy4smqwtpu

  - &minz-services-0 age1j0z95pw98qdhwnah9kcn3f8tkae299u7jsxd72gp329jfql425xswyvq8m

  - &minz-desktop age1m7d8ymts4dhvdz8fzllxwtxhy8h6q5dm4h5fvsxuv7f5t68cedeskh8ksy

creation_rules:
  - path_regex: secrets/minz-vultr-nix-0\.yaml$
    key_groups:
      - age:
          - *minz-vultr-nix-0
          - *minz-desktop

  - path_regex: secrets/minz-home-nix-0\.yaml$
    key_groups:
      - age:
          - *minz-home-nix-0
          - *minz-desktop

  - path_regex: secrets/minz-vultr-nix-1\.yaml$
    key_groups:
      - age:
          - *minz-vultr-nix-1
          - *minz-desktop

  - path_regex: secrets/minz-obs-0\.yaml$
    key_groups:
      - age:
          - *minz-obs-0
          - *minz-desktop

  - path_regex: secrets/minz-authentik-0\.yaml$
    key_groups:
      - age:
          - *minz-authentik-0
          - *minz-desktop

  - path_regex: secrets/minz-media-0\.yaml$
    key_groups:
      - age:
          - *minz-media-0
          - *minz-desktop

  - path_regex: secrets/minz-services-0\.yaml$
    key_groups:
      - age:
          - *minz-services-0
          - *minz-desktop

  - path_regex: secrets/tofu\.env$
    key_groups:
      - age:
          - *minz-vultr-nix-0
          - *minz-desktop

  - path_regex: secrets/incus-client\.yaml$
    key_groups:
      - age:
          - *minz-vultr-nix-0
          - *minz-desktop
