# Forgejo only schedules workflows from the default branch.
on:
  schedule:
    - cron: "0 5 1 * *"
  workflow_dispatch:

jobs:
  flake-update:
    runs-on: nixos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: https://github.com/DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Update flake.lock and build closures
        run: |
          nix develop --no-update-lock-file --command just ci flake-update

      - name: Push closures to Attic
        env:
          ATTIC_PUSH_TOKEN: ${{ secrets.ATTIC_PUSH_TOKEN }}
        run: |
          nix develop --no-update-lock-file --command just ci attic-push

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: flake.lock
          path: flake.lock
